name: Build binaries for all platforms and commit ZIPs

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Windows executable
        run: |
          cd dist_scripts
          pyinstaller --onefile --windowed --icon ../docs/images/talea.ico --name talea_uhi start_server.py

      - name: Create ZIP package
        run: |
          mkdir talea_uhi
          cp dist_scripts/dist/talea_uhi.exe talea_uhi/
          cp -r docs talea_uhi/
          powershell Compress-Archive -Path talea_uhi\* -DestinationPath talea_uhi-windows.zip

      - name: Prepare binaries directory
        run: |
          mkdir -p binary
          mv talea_uhi-windows.zip binary/

      - name: Pull latest binaries branch
        run: |
          git fetch origin binaries || echo "Branch binaries does not exist yet"
          git checkout -B binaries origin/binaries || git checkout -b binaries
          git pull origin binaries || echo "Nothing to pull or branch just created"

      - name: Commit Windows binary
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Add Windows binary talea_uhi-windows.zip"
          add: "binary/talea_uhi-windows.zip"
          push: --set-upstream origin binaries

  build-linux:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Linux executable
        run: |
          cd dist_scripts
          pyinstaller --onefile --windowed --name talea_uhi start_server.py

      - name: Create ZIP package
        run: |
          mkdir talea_uhi
          cp dist_scripts/dist/talea_uhi talea_uhi/
          cp -r docs talea_uhi/
          zip -r talea_uhi-linux.zip talea_uhi

      - name: Prepare binaries directory
        run: |
          mkdir -p binary
          mv talea_uhi-linux.zip binary/

      - name: Pull latest binaries branch
        run: |
          git fetch origin binaries || echo "Branch binaries does not exist yet"
          git checkout -B binaries origin/binaries || git checkout -b binaries
          git pull origin binaries || echo "Nothing to pull or branch just created"

      - name: Commit Linux binary
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Add Linux binary talea_uhi-linux.zip"
          add: "binary/talea_uhi-linux.zip"
          push: --set-upstream origin binaries

  build-macos:
    needs: build-linux
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build macOS executable
        run: |
          cd dist_scripts
          pyinstaller --onefile --windowed --name talea_uhi start_server.py

      - name: Create ZIP package
        run: |
          mkdir talea_uhi
          cp dist_scripts/dist/talea_uhi talea_uhi/
          cp -r docs talea_uhi/
          zip -r talea_uhi-macos.zip talea_uhi

      - name: Prepare binaries directory
        run: |
          mkdir -p binary
          mv talea_uhi-macos.zip binary/

      - name: Pull latest binaries branch
        run: |
          git fetch origin binaries || echo "Branch binaries does not exist yet"
          git checkout -B binaries origin/binaries || git checkout -b binaries
          git pull origin binaries || echo "Nothing to pull or branch just created"

      - name: Commit macOS binary
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Add macOS binary talea_uhi-macos.zip"
          add: "binary/talea_uhi-macos.zip"
          push: --set-upstream origin binaries

